### ISSUE TITLE
Bad tar file

### ISSUE THREAD

**Issue by WysokiStudent** [ros-noetic-arch/ros-noetic-plotjuggler#2]
When attempting to download the package from AUR one is informed that the checksum is incorrect. If the checksum is skipped this is an error one receives:
```
-> Extracting ros-noetic-plotjuggler-2.8.3.tar.gz with bsdtar
PlotJuggler-2.8.3/plotter_gui/cheatsheet/video/cheatsheet-zoom-in-out.mp4 truncated gzip input
 bsdtar: Error exit delayed from previous errors.
 ==> ERROR: Failed to unpack  ros-noetic-plotjuggler-2.8.3.tar.gz
 Cancelling
 error while building:  ros-noetic-plotjuggler
 ```
 The original message in Polish/English:
```  
-> Rozpakowywanie ros-noetic-plotjuggler-2.8.3.tar.gz za pomocą bsdtar
PlotJuggler-2.8.3/plotter_gui/cheatsheet/video/cheatsheet-zoom-in-out.mp4: truncated gzip input
bsdtar: Error exit delayed from previous errors.
==> BŁĄD: Nie udało się rozpakować ros-noetic-plotjuggler-2.8.3.tar.gz
    Przerywam...
błąd podczas budowania: ros-noetic-plotjuggler
```
My guess is that something is broken upstream, am I right?

**Comment by acxz** [comment]
Sorry for just now seeing this, it seems to have slipped my radar. The checksum should be correct, but in anycase this package is outdated, I'll update it soon.

For now I would try to delete any cache you might have and try to `yay -S ros-noetic-plotjuggler` again.

**Comment by WysokiStudent** [comment]
I did manage to build plotjuggler from source with a couple of tricks involving moving .so files around. I'll try to install this package when I have some spare time, so probably next weekend. Thanks for the response tho :)

**Comment by WysokiStudent** [comment]
I can confirm that it builds and works including plugins.
Edit: Thanks
